export const STACK_SCREENS={
BOTTOM_TAB : "BOTTOM_TAB",
PROFILE_EDIT : "PROFILE_EDIT",
RESET_PASSWORD : "RESET_PASSWORD",
}

export const BOTTOM_TAB_SCREEN={
HOME : "HOME",
UPLOAD_POST : "UPLOAD_POST",
PROFILE : "PROFILE",
}
export  const AUTH_STACK_SCREEN={
LOGIN : "LOGIN",
SIGNUP : "SIGNUP",
FORGOT_PASSWORD : "FORGOT_PASSWORD",
}